"""create_initial_tables

Revision ID: 1f5041d00621
Revises: 
Create Date: 2026-04-27 15:48:00.254541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f5041d00621'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analistas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('senha_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('analista', 'admin', name='role'), nullable=False),
    sa.Column('email_institucional', sa.String(length=200), nullable=False),
    sa.Column('email_pessoal', sa.String(length=200), nullable=True),
    sa.Column('telefone_institucional', sa.String(length=30), nullable=False),
    sa.Column('celular', sa.String(length=30), nullable=True),
    sa.Column('visibilidade_email_pessoal', sa.Boolean(), nullable=False),
    sa.Column('visibilidade_celular', sa.Boolean(), nullable=False),
    sa.Column('ministerio', sa.String(length=200), nullable=True),
    sa.Column('ministerio_sigla', sa.String(length=30), nullable=True),
    sa.Column('secretaria', sa.String(length=200), nullable=True),
    sa.Column('secretaria_sigla', sa.String(length=30), nullable=True),
    sa.Column('departamento', sa.String(length=200), nullable=True),
    sa.Column('departamento_sigla', sa.String(length=30), nullable=True),
    sa.Column('coordenacao_geral', sa.String(length=200), nullable=True),
    sa.Column('coordenacao', sa.String(length=200), nullable=True),
    sa.Column('cargo_fce', sa.String(length=100), nullable=True),
    sa.Column('portal_url', sa.Text(), nullable=True),
    sa.Column('foto_path', sa.String(length=300), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analistas_email_institucional'), 'analistas', ['email_institucional'], unique=True)
    op.create_index(op.f('ix_analistas_id'), 'analistas', ['id'], unique=False)
    op.create_table('formacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analista_id', sa.Integer(), nullable=False),
    sa.Column('nivel', sa.Enum('graduacao', 'especializacao', 'mestrado', 'doutorado', name='nivelformacao'), nullable=False),
    sa.Column('curso', sa.String(length=200), nullable=False),
    sa.Column('instituicao', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['analista_id'], ['analistas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_formacoes_id'), 'formacoes', ['id'], unique=False)
    op.create_table('temas_atuacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analista_id', sa.Integer(), nullable=False),
    sa.Column('tema', sa.String(length=200), nullable=False),
    sa.Column('em_exercicio_atual', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['analista_id'], ['analistas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temas_atuacao_id'), 'temas_atuacao', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_temas_atuacao_id'), table_name='temas_atuacao')
    op.drop_table('temas_atuacao')
    op.drop_index(op.f('ix_formacoes_id'), table_name='formacoes')
    op.drop_table('formacoes')
    op.drop_index(op.f('ix_analistas_id'), table_name='analistas')
    op.drop_index(op.f('ix_analistas_email_institucional'), table_name='analistas')
    op.drop_table('analistas')
    # ### end Alembic commands ###
